### Menu Configuration #####################
#
# Define the major menu sections and subsections in this file.
# Define where each page exists in a menu in each page's frontmatter.
# Define the order of each menu section in the `config/_default/params.toml` file with the `menuOrder` paramater
#
# See our documentation for more information about defining menus.
# https://docs.chef.io/style/front_matter/
#
# See Hugo's documentation about menus.
# https://gohugo.io/content-management/menus/
#
############################################


####
## Main Menu ##
####

[[main]]
title = "chef.io"
identifier = "chef"
url = "https://www.chef.io/"
weight = 10

[[main]]
title = "Blog"
identifier = "blog"
url = "https://www.chef.io/blog"
weight = 30

[[main]]
title = "Community"
identifier = "community"
url = "https://community.chef.io/"
weight = 40

[[main]]
title = "Training"
identifier = "training"
url = "https://www.chef.io/training"
weight = 50

[[main]]
title = "Downloads"
identifier = "downloads"
url = "https://www.chef.io/downloads"
weight = 60

####
## End Main Menu ##
####

[[install]]
title = "Install"
identifier = "install"

[[upgrade]]
title = "Upgrade"
identifier = "upgrade"

[[builder]]
title = "Builder"
identifier = "builder"

    [[builder]]
    title = "On-Prem Builder"
    identifier  = "builder/on-prem"
    parent = "builder"
    weight = "20"

        [[builder]]
        title = "Install"
        identifier  = "builder/on-prem/install"
        parent = "builder/on-prem"
        weight = "20"

        [[builder]]
        title = "Configure"
        identifier  = "builder/on-prem/configure"
        parent = "builder/on-prem"
        weight = "30"

        [[builder]]
        title = "Manage"
        identifier  = "builder/on-prem/manage"
        parent = "builder/on-prem"
        weight = "40"

        [[builder]]
        title = "Origins"
        identifier  = "builder/on-prem/origins"
        parent = "builder/on-prem"
        weight = "50"

        [[builder]]
        title = "Packages"
        identifier  = "builder/on-prem/packages"
        parent = "builder/on-prem"
        weight = "50"

    [[builder]]
    title = "SaaS Builder"
    identifier  = "builder/saas"
    parent = "builder"
    weight = "30"

[[origins]]
title = "Origins"
identifier = "origins"

[[packages]]
title = "Packages"
identifier = "packages"

[[plans]]
title = "Plans"
identifier = "plans"

[[services]]
title = "Services"
identifier = "services"

[[sup]]
title = "Supervisors"
identifier = "supervisors"

[[reference]]
title = "Reference"
identifier = "reference"

    [[reference]]
    title = "APIs"
    identifier  = "reference/api"
    parent = "reference"
    weight = "20"

[[containers]]
title = "Containers"
identifier = "containers"

[[sup_packages]]
title = "Supported packages"
identifier = "sup_packages"

[[release_notes]]
title = "Release notes"
identifier = "release_notes"
url = "https://docs.chef.io/release_notes_habitat/"
