### Menu Configuration #####################
#
# Define the major menu sections and subsections in this file.
# Define where each page exists in a menu in each page's frontmatter.
# Define the order of each menu section in the `config/_default/params.toml` file with the `menuOrder` paramater
#
# See our documentation for more information about defining menus.
# https://docs.chef.io/style/front_matter/
#
# See Hugo's documentation about menus.
# https://gohugo.io/content-management/menus/
#
############################################


####
## Main Menu ##
####

[[main]]
title = "chef.io"
identifier = "chef"
url = "https://www.chef.io/"
weight = 10

[[main]]
title = "Blog"
identifier = "blog"
url = "https://www.chef.io/blog"
weight = 30

[[main]]
title = "Community"
identifier = "community"
url = "https://community.chef.io/"
weight = 40

[[main]]
title = "Training"
identifier = "training"
url = "https://www.chef.io/training"
weight = 50

[[main]]
title = "Downloads"
identifier = "downloads"
url = "https://www.chef.io/downloads"
weight = 60

####
## End Main Menu ##
####

[[oveview]]
title = "Overview"
identifier = "chef_habitat/overview"
weight = 10

[[habitat]]
title = "Habitat"
identifier = "chef_habitat/habitat"
weight = 20

[[builder]]
title = "Builder"
identifier = "chef_habitat/builder"
weight = 30

[[packages]]
title = "Packages"
identifier = "chef_habitat/packages"
weight = 40

# [[overview.overview]]
# title = "Overview"
# identifier = "overview"
#
# [[habitat.install]]
# title = "Install"
# identifier = "install"
#
# [[habitat.upgrade]]
# title = "Upgrade"
# identifier = "upgrade"
#
# [[habitat.origins]]
# title = "Origins"
# identifier = "origins"
#
# [[habitat.packages]]
# title = "Packages"
# identifier = "packages"
#
# [[habitat.plans]]
# title = "Plans"
# identifier = "plans"
#
# [[habitat.services]]
# title = "Services"
# identifier = "services"
#
# [[habitat.sup]]
# title = "Supervisors"
# identifier = "supervisors"
#
# [[habitat.reference]]
# title = "Reference"
# identifier = "reference"
#
#     [[habitat.reference]]
#     title = "APIs"
#     parent = "reference"
#     identifier  = "reference/api"
#     weight = "20"
#
# [[habitat.containers]]
# title = "Containers"
# identifier = "containers"
#
# [[habitat.release_notes]]
# title = "Release notes"
# identifier = "release_notes"
#
