### Menu Configuration #####################
#
# Define the major menu sections and subsections in this file.
# Define where each page exists in a menu in each page's frontmatter.
# Define the order of each menu section in the `config/_default/params.toml` file with the `menuOrder` paramater
#
# See our documentation for more information about defining menus.
# https://docs.chef.io/style/front_matter/
#
# See Hugo's documentation about menus.
# https://gohugo.io/content-management/menus/
#
############################################


####
## Main Menu ##
####

[[main]]
title = "chef.io"
identifier = "chef"
url = "https://www.chef.io/"
weight = 10

[[main]]
title = "Blog"
identifier = "blog"
url = "https://www.chef.io/blog"
weight = 30

[[main]]
title = "Community"
identifier = "community"
url = "https://community.chef.io/"
weight = 40

[[main]]
title = "Training"
identifier = "training"
url = "https://www.chef.io/training"
weight = 50

[[main]]
title = "Downloads"
identifier = "downloads"
url = "https://www.chef.io/downloads"
weight = 60

####
## End Main Menu ##
####

[[oveview]]
title = "Overview"
identifier = "chef_habitat/overview"
weight = 10

[[habitat]]
title = "Chef Habitat Core"
identifier = "chef_habitat/habitat"
weight = 20

[[builder]]
title = "Chef Habitat Builder"
identifier = "chef_habitat/builder"
weight = 30

[[packages]]
title = "Chef Habitat Packages"
identifier = "chef_habitat/packages"
weight = 40
